package Runnable;

public class Constructorexception {
	
	
	Constructorexception() throws ArithmeticException
	{
		System.out.println("i const");
		int i = 10/0;
		
		
		
	}
	
	
	public static void main(String[] args) {
	try {	
		Constructorexception ty = new Constructorexception();
		
	}
	
	catch(Exception e) { }
		System.out.println("Afetr");
		
		
	}

}
